-intstyle "ise" -incremental -o "C:/Dev/DLP/Dispositivos-Logicos-Programaveis-SSI/Mestre/slave_isim_beh.exe" -prj "C:/Dev/DLP/Dispositivos-Logicos-Programaveis-SSI/Mestre/slave_beh.prj" "work.slave" 
